name: The iceberg data collection
on:
  push:
    branches:
      - main
      - try

jobs:
  runner-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirement.txt

      - name: Connect to PostgreSQL
        run: |
          bash download_products.bash
          py.test
