name: The iceberg data collection
on:
  push:
    branches:
      - main
      - try

jobs:
  runner-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --volume /home/runner/work/large-file-processor-postman/large-file-processor-postman:/data
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download products csv file
        run: bash download_products.bash

      - name: Connect to PostgreSQL
        run: py.test

      - name: Save the logfile
        uses: actions/upload-artifact@v2
        with:
          name: Log File
          path: logfile.log